### ISSUE TITLE
Got "Device not found" (looks like android.permission.BLUETOOTH_CONNECT is required)

### ISSUE THREAD

**Issue by melianmiko** [TheLastGimbus/FreeBuddy#2]
Application can't find my HUAWEI FreeBuds 4i. Official apps work fine

- Device: Samsung A32 4G
- Android 13
- Location access is granted

![image](https://user-images.githubusercontent.com/67851274/210508308-d7d7d592-7684-4858-9c97-9d505ea2c14e.png)
![image](https://user-images.githubusercontent.com/67851274/210508354-379d9f64-f330-4c0b-92db-290b2d511e60.png)

**Comment by melianmiko** [comment]
This error infinitely goes to logcat:
```
01-04 14:50:35.025 30271 30271 E MethodChannel#flutter_bluetooth_serial/methods: Failed to handle method call
01-04 14:50:35.025 30271 30271 E MethodChannel#flutter_bluetooth_serial/methods: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10313, packageName = com.lastgimbus.the.freebuddy, attributionTag = null, token = android.os.BinderProxy@814ea9a, next = null }: AdapterService getBondedDevices
01-04 14:50:35.025 30271 30271 E MethodChannel#flutter_bluetooth_serial/methods:        at com.android.bluetooth.Utils.checkPermissionForDataDelivery(Utils.java:901)
01-04 14:50:35.025 30271 30271 E MethodChannel#flutter_bluetooth_serial/methods:        at com.android.bluetooth.Utils.checkConnectPermissionForDataDelivery(Utils.java:933)
01-04 14:50:35.025 30271 30271 E MethodChannel#flutter_bluetooth_serial/methods:        at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.getBondedDevices(AdapterService.java:2888)
01-04 14:50:35.025 30271 30271 E MethodChannel#flutter_bluetooth_serial/methods:        at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.getBondedDevices(AdapterService.java:2880)
01-04 14:50:35.025 30271 30271 E MethodChannel#flutter_bluetooth_serial/methods:        at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:1080)
01-04 14:50:35.025 30271 30271 E MethodChannel#flutter_bluetooth_serial/methods:        at android.os.Binder.execTransactInternal(Binder.java:1321)
01-04 14:50:35.025 30271 30271 E MethodChannel#flutter_bluetooth_serial/methods:        at android.os.Binder.execTransact(Binder.java:1280)
01-04 14:50:35.026 30271 30314 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10313, packageName = com.lastgimbus.the.freebuddy, attributionTag = null, token = android.os.BinderProxy@814ea9a, next = null }: AdapterService getBondedDevices, null, java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10313, packageName = com.lastgimbus.the.freebuddy, attributionTag = null, token = android.os.BinderProxy@814ea9a, next = null }: AdapterService getBondedDevices
01-04 14:50:35.026 30271 30314 E flutter :      at com.android.bluetooth.Utils.checkPermissionForDataDelivery(Utils.java:901)
01-04 14:50:35.026 30271 30314 E flutter :      at com.android.bluetooth.Utils.checkConnectPermissionForDataDelivery(Utils.java:933)
01-04 14:50:35.026 30271 30314 E flutter :      at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.getBondedDevices(AdapterService.java:2888)
01-04 14:50:35.026 30271 30314 E flutter :      at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.getBondedDevices(AdapterService.java:2880)
01-04 14:50:35.026 30271 30314 E flutter :      at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:1080)
01-04 14:50:35.026 30271 30314 E flutter :      at android.os.Binder.execTransactInternal(Binder.java:1321)
01-04 14:50:35.026 30271 30314 E flutter :      at android.os.Binder.execTransact(Binder.java:1280)
01-04 14:50:35.026 30271 30314 E flutter : )
01-04 14:50:35.026 30271 30314 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
01-04 14:50:35.026 30271 30314 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296)
01-04 14:50:35.026 30271 30314 E flutter : <asynchronous suspension>
01-04 14:50:35.026 30271 30314 E flutter : #2      FlutterBluetoothSerial.getBondedDevices (package:flutter_bluetooth_serial/FlutterBluetoothSerial.dart:197)
01-04 14:50:35.026 30271 30314 E flutter : <asynchronous suspension>
01-04 14:50:35.026 30271 30314 E flutter : #3      HeadphonesConnectionCubit._setupTryConnectingStream.<anonymous closure> (package:freebuddy/headphones/headphones_connection_cubit.dart:27)
01-04 14:50:35.026 30271 30314 E flutter : <asynchronous suspension>
01-04 14:50:35.026 30271 30314 E flutter : #4      loopStream.loop (package:freebuddy/headphones/headphones_connection_cubit.dart:113)
01-04 14:50:35.026 30271 30314 E flutter : <asynchronous suspension>
```

**Comment by TheLastGimbus** [comment]
Oh, you have Android >=12 :confused: I'm already writing a plugin to support that: https://github.com/TheLastGimbus/the_last_bluetooth but it will take some time 😬

**Comment by TheLastGimbus** [comment]
With a help of @expo1337, we fixed it :sunglasses: 

Try it out now!

**Comment by melianmiko** [comment]
> Try it out now!

Sorry,but... I can't =)

A few days ago I downgraded my device to Android 11, due to Mir Pay (our GooglePlay alternative), which don't work on Android 13. I'll check that a bit later...

**Comment by melianmiko** [comment]
Checked, current Google Play works fine =)
