### ISSUE TITLE
Poco F3, miui 13

### ISSUE THREAD

**Issue by nazarsavorona** [TheLastGimbus/FreeBuddy#5]
Crashes when headphones are connected.

**Comment by TheLastGimbus** [comment]
Hi! Do You maybe have multiple devices paired as in #4 ?

If not, are you able to send me android logs when app crashes?

**Comment by nazarsavorona** [comment]
How can I export them?

**Comment by TheLastGimbus** [comment]
Oh, you would need to have debugging enabled in your phone, install `adb` on your pc, then connect phone to pc etc

it's fairly complicated to do so don't bother if you don't have much time

but if you would like to help with the app, i can guide you :)

**Comment by andreyplus** [comment]
Hello, the application crashes when connecting headphones. (MIUI 13, Android 12)

<details> 
  <summary>In the logs:</summary>
<pre>
E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
E AndroidRuntime: Process: com.lastgimbus.the.freebuddy, PID: 19019
E AndroidRuntime: java.lang.SecurityException: UID 10967 / PID 19019 lacks permission android.permission.BLUETOOTH
E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2409)
E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2392)
E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2334)
E AndroidRuntime:        at android.bluetooth.IBluetoothSocketManager$Stub$Proxy.connectSocket(IBluetoothSocketManager.java:227)
E AndroidRuntime:        at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:404)
E AndroidRuntime:        at s2.c$g.invokeSuspend(Unknown Source:24)
E AndroidRuntime:        at s2.c$g.invoke(Unknown Source:8)
E AndroidRuntime:        at s2.c$g.invoke(Unknown Source:4)
E AndroidRuntime:        at r4.b.b(Unknown Source:7)
E AndroidRuntime:        at kotlinx.coroutines.l.e(Unknown Source:49)
E AndroidRuntime:        at kotlinx.coroutines.j.g(Unknown Source:0)
E AndroidRuntime:        at s2.c.r(Unknown Source:103)
E AndroidRuntime:        at s2.c.b(Unknown Source:0)
E AndroidRuntime:        at s2.c$k.invokeSuspend(Unknown Source:51)
E AndroidRuntime:        at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:11)
E AndroidRuntime:        at kotlinx.coroutines.b1.run(Unknown Source:88)
E AndroidRuntime:        at kotlinx.coroutines.internal.k.run(Unknown Source:12)
E AndroidRuntime:        at kotlinx.coroutines.scheduling.k.run(Unknown Source:2)
E AndroidRuntime:        at kotlinx.coroutines.scheduling.a.s(Unknown Source:0)
E AndroidRuntime:        at kotlinx.coroutines.scheduling.a$c.d(Unknown Source:14)
E AndroidRuntime:        at kotlinx.coroutines.scheduling.a$c.n(Unknown Source:28)
E AndroidRuntime:        at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
</pre>
</details>

Perhaps this is due to https://stackoverflow.com/questions/71552331/got-lacks-permission-android-permission-bluetooth-on-specific-device-after-and

**Comment by TheLastGimbus** [comment]
Omg @andreyplus this is precious for me - i did see security exceptions in google play console, and i thought "huh xiaomis implementation probably still want location permission for basic shit, I'm not doing that"

But a single line in manifest! Will fix this very soon ✌️✌️

**Comment by andreyplus** [comment]
@TheLastGimbus Hi, how's the progress?

**Comment by andreyplus** [comment]
@TheLastGimbus Thanks, this works great!

**Comment by TheLastGimbus** [comment]
Fantastic, will land in next official release :tada:
